### ISSUE TITLE
Picasso integration issue

### ISSUE THREAD

**Issue by gwrn** [yayaa/ParallaxListView#1]
Hi,

I cant make your library work with Picasso. In sample instead of setting image resource I'm doing sometinhg like that:

```
Picasso.with(context).load("url-to-image").into(new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                viewHolder.getBackgroundImage().setImageBitmap(bitmap);
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {
            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {
            }
        });
```

Image is being loaded and set to view but there is no parallax effect. I tried other variation but couldn't make it work correctly. Am I doing something wrong? Can you help mi with that?

Picasso dependency:
`compile 'com.squareup.picasso:picasso:2.5.2'`

**Comment by yayaa** [comment]
This is not an issue, but i updated library's sample project just to show how to handle it simply. 
Please see [the sample.](https://github.com/yayaa/ParallaxListView/blob/master/sample/app/src/main/java/com/yayandroid/parallaxlistview/sample/TestAdapter.java)

**Comment by gwrn** [comment]
Yes it works. My fault. I didn't check everything carefully.
