### ISSUE TITLE
Image is not expanding to full width

### ISSUE THREAD

**Issue by devilonbike** [yayaa/ParallaxListView#3]
XML Layout:-

```
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="200dp">

    <com.yayandroid.parallaxlistview.ParallaxImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</FrameLayout>
```

getView from adaptor

```
@Override
public View getView(int position, View view, ViewGroup parent) {
    ViewHolder viewHolder;

    if (view == null) {

        view = inflater.inflate(R.layout.item_main , parent, false);

        viewHolder = new ViewHolder(view);
        viewHolder.itemView = view;
        viewHolder.setBackgroundImage((ParallaxImageView) view.findViewById(R.id.iv_item_main));
        view.setTag(viewHolder);
    } else {
        viewHolder = (ViewHolder) view.getTag();
    }
    MainScreen mainScreen = mainScreenList.get(position);

    viewHolder.ll_item_main_content.setVisibility(View.GONE);

        viewHolder.fl_item_main_advert.setVisibility(View.VISIBLE);
        Picasso.with(_context).load(mainScreen.getBgImage().getUrl()).into(viewHolder.getBackgroundImage());

        viewHolder.tv_item_main_title_advert.setText(mainScreen.getTitle());
        viewHolder.tv_item_main_description_advert.setText(mainScreen.getDescription());


    viewHolder.getBackgroundImage().reuse();
    return view;
}
```

**Comment by zentechdatle** [comment]
you can change,

Picasso.with(context).load(imageUrls[position % imageUrls.length]).resize(1200,600)
            .into(viewHolder.getBackgroundImage());

**Comment by yayaa** [comment]
I have no idea what code spects you have, but i guess it may, somehow, related to have FrameLayout as your rootView. Because i used exactly same codes except having RelativeLayout as rootView instead of FrameLayout. Check the [sample](https://github.com/yayaa/ParallaxListView/tree/master/sample) please.

**Comment by jamesalester** [comment]
Was this ever solved? I'm having the same problem except I'm using a Relative Layout like in the sample.

**Comment by yayaa** [comment]
Yes, actually i made a fix about it and now updated this library as well, you can use v1.1 to have it work. But please check [this issue and comments](https://github.com/yayaa/ParallaxRecyclerView/issues/2#issuecomment-223203527) for further information on this topic.
