### ISSUE TITLE
Not an Issue,need help.

### ISSUE THREAD

**Issue by devqualwebs** [yayaa/ParallaxListView#5]
Hello,

This isn't a issue of your library but any help would be great.

I use your source code and changed the ParallaxListview extends by expandable list view and did some changes accordingly.

everything is working fine parallax,scrollling but when I click on any item present in the Expandable listview to see child of that group app get crashed in ParallaxListview at onScroll with the error

 ["Attempt to invoke virtual method 'boolean com.qualwebs.expandablefinal.parallax.ParallaxImageView.doTranslate()' on a null object reference"]

**Comment by devqualwebs** [comment]
Solved it.

I was inflating the child view using the parallax view holder which was causing that Null Pointer Exception.

Your repo is great..

**Comment by yayaa** [comment]
As it's said "on a null object reference" i would've said that you were trying to use a view that has no ParallaxImageView in it. 

I'm glad that you solve it by yourself though. And thanks for the compliment :)
