### ISSUE TITLE
Images don't fill width of screen

### ISSUE THREAD

**Issue by jamesalester** [yayaa/ParallaxListView#6]
I love this ParallaxListView and it works great for the images that fill the screen but most of them don't. Most don't fill the width of the screen and have grey space next to them. The ParallaxImageView's layout_width is set to match_parent. I've tried subclassing ParallaxImageView and setting the minimumWidth to the width of the screen but that doesn't work either. I've attached a screenshot. I'm new to Android so any help would be appreciated.

![screenshot_2016-06-04-19-26-20](https://cloud.githubusercontent.com/assets/19751644/15801375/b5097c1e-2a8a-11e6-9d60-1a93f2cd3e23.png)

**Comment by yayaa** [comment]
Updated the library, you can use v1.1 to have it work. But please check [this issue and comments](https://github.com/yayaa/ParallaxRecyclerView/issues/2#issuecomment-223203527) for further information on this topic.
